---
title: "HW3"
author: "Blain Morin"
date: "October 23, 2018"
output: pdf_document
header-includes:
- \usepackage{float}
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}

### Load required libraries
library(readr)
library(lme4)
library(tidyr)
library(nlme)
library(stargazer)
library(dplyr)
library(ggplot2)
library(extrafont)
library(extrafontdb)
library(grid)
library(gridExtra)

```

# Question 1:

```{r, echo = FALSE, message = FALSE, warning = FALSE}

### Load and clean data
mcalindon = read_csv("McAlindon_Big.csv")

weather = mcalindon %>%
  select(ID, WeatherDate, avgtemp, age, race2, inccat, treat, sex, retire, nsaid)

pains = mcalindon %>%
  select(ID, pain.1, pain.2, pain.3, pain.4, pain.4, pain.5, pain.6, pain.7) %>%
  group_by(ID) %>%
  slice(1) 
  
pains = pains %>%
  gather(key = pain.time, value = pain.score, pain.1:pain.7 ) %>%
  group_by(ID) %>%
  mutate( index = row_number(ID))

days = mcalindon %>%
  select(ID, lastdt1, lastdt2, lastdt3, lastdt4, lastdt5, lastdt6, lastdt7) %>%
  group_by(ID) %>%
  slice(1)

days = days %>%
  gather(key = time.name, value = day, lastdt1:lastdt7) %>%
  mutate(index = row_number(ID))

pain.w.days = pains %>%
  inner_join(days)

Q1 = pain.w.days %>%
  rename(WeatherDate = day) %>%
  inner_join(weather) 


### Relevel Factors
Q1 = Q1 %>%
  mutate(female = ifelse(sex == 2, 1, 0)) %>%
  mutate(retired = ifelse(retire == 2, 1, 0))


### Start each person at day zero

Q1 = Q1 %>%
  group_by(ID) %>%
  mutate(day = WeatherDate - min(WeatherDate)) %>%
  ungroup()

```



```{r, results = 'asis', echo = FALSE, message = FALSE}

###Summary table

variables1 = Q1 %>%
  select(pain.score, avgtemp, age, race2, inccat, treat, female, retired, nsaid)

table1 = model.matrix(~ pain.score + avgtemp + age + race2 + as.factor(inccat) + treat + female + retired + nsaid - 1, 
                    data = variables1)

stargazer(as.data.frame(table1),
          title = "Summary Statistics",
          table.placement = "H",
          header = FALSE,
          summary.stat = c("mean", "sd", "min", "max", "n"),
          covariate.labels = c(
            "Pain Score",
            "Average Temperature (F)",
            "Age",
            "White or Hispanic",
            "Income < 15k",
            "Income 15 - 35k",
            "Income 35 - 55k",
            "Income 55 - 75k",
            "Income > 75k",
            "Treatment Group = 1",
            "Female = 1",
            "Retired = 1",
            "NSAIDs = 1"
          ))


```

```{r, echo = FALSE, results = 'asis'}

### Start with full model

mm1.Q1 = lmer(pain.score ~ (1 + scale(avgtemp) + day| ID) +
                scale(avgtemp) +
                day +
                scale(age) +
                as.factor(race2) + 
                as.factor(inccat) + 
                as.factor(treat) + 
                as.factor(female) + 
                as.factor(retired) + 
                as.factor(nsaid),
             data = Q1)

mm2.Q1 = lmer(pain.score ~ (1 + day| ID) +
                scale(avgtemp) +
                day +
                scale(age) +
                as.factor(race2) +  
                as.factor(treat) + 
                as.factor(female) + 
                as.factor(nsaid),
             data = Q1,
             na.action = na.exclude,
             control = lmerControl(optCtrl=list(max=100000000)))

mm3.Q1 = lmer(pain.score ~ (1 + scale(avgtemp)| ID) +
                scale(avgtemp) +
                day +
                scale(age) +
                as.factor(race2) +  
                as.factor(treat) + 
                as.factor(female) + 
                as.factor(nsaid),
             data = Q1,
             control = lmerControl(optCtrl=list(max=100000000)))

mm4.Q1 = lmer(pain.score ~ (1 + day| ID) +
                scale(avgtemp) +
                day +
                day:treat +
                scale(age) +  
                as.factor(treat) + 
                as.factor(nsaid),
             data = Q1,
             control = lmerControl(optCtrl=list(max=1000000000)))


stargazer(mm1.Q1, mm2.Q1, mm3.Q1, mm4.Q1,
          title = "Regression Results",
          table.placement = "H",
          header = FALSE,
          dep.var.labels = c("Pain Score"),
          column.labels = c("Rand Slopes (Temp, Day)", 
                              "Rand Slope (Day)", 
                              "Rand Slope (Temp)",
                              "Rand Slope (Day)"),
          covariate.labels = c("Avg Temp",
                               "Day",
                               "Age",
                               "White or Hispanic",
                               "Income 15 - 35k",
                               "Income 35 - 55k",
                               "Income 55 - 75k",
                               "Income > 75k",
                               "Treatment",
                               "Female",
                               "Retired",
                               "Using NSAIDs",
                               "Day * Treatment"))


```


```{r, echo = FALSE}

### Observed vs Predicted for nine people

nine = Q1 %>%
  mutate(fit = fitted(mm2.Q1)) %>%
  filter(ID %in% c(178, 180, 237, 315, 447, 469, 499, 581, 737)) %>%
  mutate(ID = as.factor(ID))

nine %>%
  ggplot(aes(x = day, y = pain.score, color = ID)) +
  geom_point(size=3, show.legend = FALSE) + 
  geom_line( aes(y = fit), size=1, show.legend = FALSE) +
  facet_wrap(~ID) +
  ylab("Pain Score") +
  xlab("Day") +
  ggtitle("Observed vs Predicted for Nine Random Inidivuals") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans"), strip.background = element_blank())
  
```

```{r, fig.height=12, fig.width=12, echo = FALSE}

### Random Effects Plot

yy = ranef(mm2.Q1, condVar = TRUE)

ranef.data = as.data.frame(yy)

ints = ranef.data %>%
  filter(term == "(Intercept)")

slope = ranef.data %>%
  filter(term == "day")

slope$ordered = reorder(slope$grp, slope$condval)

labelss = c("Intercept")

int = ggplot(ints, aes(y=grp, x=condval))+
  geom_point()+
  geom_errorbarh(aes(xmin=condval-2*condsd,xmax=condval+2*condsd),height=0) +
  theme_classic() +
  ylab("Person ID") +
  xlab("Slope Value") + 
  ggtitle("Random Intercepts") +
  theme(text=element_text(size=12,  family="CM Sans"))

slopes = ggplot(slope, aes(y=ordered, x=condval))+
  geom_point()+
  geom_errorbarh(aes(xmin=condval-2*condsd, xmax=condval+2*condsd),height=0) +
  theme_classic() +
  ylab("Person ID") +
  xlab("Intercept Value") + 
  ggtitle("Random Slopes on Day") +
  theme(text=element_text(size=12,  family="CM Sans"))

grid.arrange(int, slopes, nrow = 1)



```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

### Residuals plot

Q1 = Q1 %>%
  mutate(resids = resid(mm2.Q1))

Q1 %>% 
  ggplot(aes(sample = resids)) + 
  stat_qq() + 
  stat_qq_line() +
  theme_classic() +
  ylab("Sample Quantile") +
  xlab("Theoretical Quantile") +
  ggtitle("Residuals QQ Plot") +
  theme(text=element_text(size=12,  family="CM Sans"))



```


# Question 2:

```{r, warning = FALSE, echo = FALSE, results='asis'}

### Data Cleaning
srrs = read.csv("srrs2.txt")

min.srrs = srrs %>%
  filter(state2 == "MN") %>%
  select(idnum, state2, stfips, typebldg, floor, basement, activity, county, cntyfips)

city = read.csv("cty.txt")

min.city = city %>%
  filter(st == "MN") %>%
  select(stfips, ctfips, st, cty, Uppm)  %>%
  rename(cntyfips = ctfips) %>%
  group_by(stfips, cntyfips) %>%
  slice(1) %>%
  ungroup()

Q2 = inner_join(min.srrs, min.city, by = "cntyfips")

Q2 = Q2 %>%
  mutate(has.basement = as.integer(basement)) %>%
  mutate(has.basement = as.factor(ifelse(has.basement == 3, 0, ifelse(has.basement == 4, 1 , NA)))) %>%
  mutate(is.sfh = as.factor(ifelse(typebldg == 1, 1, 0))) %>%
  mutate(which.floor = as.factor(ifelse(floor == 1, 1, ifelse(floor == 9, NA, 0)))) %>%
  mutate(log.activity = log(I(activity+.00001))) %>%
  mutate(log.Uppm = log(I(Uppm+.0000001)))  %>%
  filter(complete.cases(.))
  
  
```


```{r, echo = FALSE, results = 'asis'}

### Summary table

variables = Q2 %>% 
  select(activity, which.floor, has.basement, is.sfh, county, Uppm)

variables = model.matrix(~activity + which.floor + has.basement + is.sfh + Uppm - 1, data = variables)

variables = as.data.frame(variables)

stargazer(variables, 
          header = FALSE,
          table.placement = "H",
          summary.stat = c("mean", "sd", "min", "max", "n"),
          title = "Summary Statistics")



```



```{r, echo = FALSE, results = 'asis'}

### Run model

mm.Q2 = lmer(log.activity ~ 
               which.floor + 
               has.basement + 
               is.sfh + 
               log.Uppm +
               (1 + log.Uppm | cntyfips), 
             data = Q2)  

stargazer(mm.Q2, header = FALSE, table.placement = 'H')


```

```{r, fig.height=12, fig.width=12, echo = FALSE}

### Random Effects Plot

yy = ranef(mm.Q2, condVar = TRUE)

ranef.data = as.data.frame(yy)

ggplot(ranef.data, aes(y=grp,x=condval))+
  geom_point()+
  facet_wrap( ~ term, scales="free_x")+
  geom_errorbarh(aes(xmin=condval-2*condsd,xmax=condval+2*condsd),height=0) +
  theme_classic() +
  ylab("County ID") +
  xlab("Intercept or Slope Value") + 
  ggtitle("County Random Effect Distibutions") +
  theme(text=element_text(size=12,  family="CM Sans"), strip.background = element_blank())

```

```{r, echo = FALSE, fig.width=12, fig.height=8}

### Predicted vs Observed

Q22 = Q2 %>%
  mutate(model.prediction = fitted(mm.Q2)) %>%
  mutate(resids = residuals(mm.Q2))

test = Q22 %>%
  group_by(county) %>%
  arrange(county) %>%
  slice(1) %>%
  ungroup()

ggplot(data = test, aes(x = as.factor(idnum))) +
  geom_point(aes(y = activity)) +
  geom_point(aes(y = model.prediction, color = "red"), show.legend = FALSE) +
  geom_segment(aes(xend = as.factor(idnum), y = model.prediction, yend = activity),
               arrow = arrow(length = unit(0.2, "line")), 
               color="red") + 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("House ID Number") +
  ylab("log(Radon Level)") + 
  ggtitle("Predicted (Black) vs Observed (Red) for 1 House from Each County") +
  theme(text=element_text(size=12,  family="CM Sans"))

```

```{r, echo = FALSE}

### Residuals QQ Plot

Q22 %>% 
  ggplot(aes(sample = resids)) + 
  stat_qq() + 
  stat_qq_line() +
  theme_classic() +
  ylab("Sample Quantile") +
  xlab("Theoretical Quantile") +
  ggtitle("Residuals QQ Plot") +
  theme(text=element_text(size=12,  family="CM Sans"))
  

```







